# Mapping and Sort
FROM alpine:3.20.3 

# Install necessary packages
RUN apk update && \
    apk add --no-cache \
    bash \
    vim \
    ca-certificates \
    zlib-dev \
    bzip2-dev \
    wget \
    build-base \
    ncurses-dev \
    xz-dev \
    coreutils \
    libdeflate \
    isa-l \
    libdeflate-dev \
    isa-l-dev \
    util-linux

WORKDIR /software

# samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 && \
    tar -jxvf samtools-1.21.tar.bz2 && \
    rm samtools-1.21.tar.bz2 && \
    cd samtools-1.21 && \
    ./configure --prefix $(pwd) && \
    make && \
    cp samtools /usr/local/bin/ && \
    rm -rf /software/samtools-1.21

# bwa
RUN wget https://github.com/lh3/bwa/archive/refs/tags/v0.7.18.zip && \
    unzip v0.7.18.zip && \
    cd bwa-0.7.18 && \
    make && \
    cp bwa /usr/local/bin/ && \
    cd .. && \
    rm -rf /software/v0.7.18.zip && \
    rm -rf /software/bwa-0.7.18

# sambamba
RUN wget https://github.com/biod/sambamba/releases/download/v1.0.1/sambamba-1.0.1-linux-amd64-static.gz && \
    gunzip sambamba-1.0.1-linux-amd64-static.gz && \
    mv sambamba-1.0.1-linux-amd64-static /usr/local/bin/ && \
    chmod 777 /usr/local/bin/sambamba-1.0.1-linux-amd64-static && \
    ln -s /usr/local/bin/sambamba-1.0.1-linux-amd64-static /usr/local/bin/sambamba

# bamdst
RUN wget https://github.com/shiquan/bamdst/archive/refs/heads/master.zip && \
    unzip master.zip && \
    cd bamdst-master && \
    make && \
    cp bamdst /usr/local/bin/ && \
    rm -rf /software/master.zip && \
    rm -rf /software/bamdst-master

# fastp
RUN wget https://github.com/OpenGene/fastp/archive/refs/heads/master.zip && \
    unzip master.zip && \
    cd fastp-master && \
    make -j && \
    make install && \
    rm -rf /software/master.zip && \
    rm -rf /software/fastp-master

# default command
WORKDIR /usr/local/bin/
ENV PATH="/usr/local/bin/:${PATH}"
CMD ["/bin/bash"]

