# Illumina Manta Structural Variant Caller
# https://github.com/Illumina/manta
# v1.6.0

FROM centos:6
MAINTAINER pzweuj

# 安装依赖
RUN yum install -y \
    python2 \
    wget \
    bash \
    bzip2 && \
    yum clean all

# Manta 1.6.0
WORKDIR /software
RUN wget https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.centos6_x86_64.tar.bz2 && \
    tar -jxvf manta-1.6.0.centos6_x86_64.tar.bz2 && \
    rm manta-1.6.0.centos6_x86_64.tar.bz2 && \
    rm -rf manta-1.6.0.centos6_x86_64/share/demo

# 环境变量
ENV PATH=/software/manta-1.6.0.centos6_x86_64/bin:$PATH

# 工作目录
WORKDIR /data/

# 默认命令
CMD ["/bin/bash"]
