# 基础镜像
FROM etal/cnvkit:0.9.11

# 切换用户调整脚本权限
USER root
RUN chmod 777 /opt/conda/lib/python3.10/site-packages/cnvlib/params.py 

# 安装补丁
RUN wget -O /opt/conda/bin/cnvkit_params_modify.py https://github.com/pzweuj/MyDockerImagePublic/raw/refs/heads/main/cnvkit/cnvkit_params_modify.py

# 切换回去
USER ubuntu
CMD ["bash"]

# Maintainer
LABEL author="Eric Talevich <52723+etal@users.noreply.github.com>" maintainer="pzweuj"
