FROM alpine:3.20.3

# 安装基础依赖
RUN apk add --no-cache \
    git \
    perl \
    R \
    R-dev \
    build-base \
    perl-dev \
    wget \
    bash \
    autoconf \
    automake \
    libtool \
    zlib-dev \
    bzip2-dev \
    xz-dev \
    curl-dev

# 安装 bcftools
RUN cd /tmp && \
    git clone --recurse-submodules https://github.com/samtools/htslib.git && \
    git clone https://github.com/samtools/bcftools.git && \
    cd bcftools && \
    make && \
    make install && \
    cd .. && \
    rm -rf /tmp/bcftools /tmp/htslib

# 安装bedtools
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
    mv bedtools.static /usr/local/bin/bedtools && \
    chmod a+x /usr/local/bin/bedtools

# 克隆AutoMap仓库
RUN git clone https://github.com/mquinodo/AutoMap.git /opt/AutoMap

# 设置工作目录
WORKDIR /opt/AutoMap

# 添加到PATH
ENV PATH="/opt/AutoMap:${PATH}"

# 设置默认命令行为bash
CMD ["/bin/bash"]

