FROM alpine:3.20.3

# 安装基础依赖
RUN apk add --no-cache \
    git \
    perl \
    R \
    R-dev \
    bcftools \
    bedtools \
    build-base \
    perl-dev \
    wget \
    bash

# 克隆AutoMap仓库
RUN git clone https://github.com/mquinodo/AutoMap.git /opt/AutoMap

# 设置工作目录
WORKDIR /opt/AutoMap

# 添加到PATH
ENV PATH="/opt/AutoMap:${PATH}"

# 设置默认命令行为bash
CMD ["/bin/bash"]

