analysis:
  analysisMode: PASS_ONLY
  frequencySources:
  - THOUSAND_GENOMES
  - GNOMAD_E_AFR
  - GNOMAD_E_AMR
  - GNOMAD_E_EAS
  - GNOMAD_E_NFE
  - GNOMAD_E_SAS
  - GNOMAD_G_AFR
  - GNOMAD_G_AMR
  - GNOMAD_G_EAS
  - GNOMAD_G_NFE
  - GNOMAD_G_SAS
  genomeAssembly: hg19
  hpoIds:
  inheritanceModes:
    AUTOSOMAL_DOMINANT: 0.1
    AUTOSOMAL_RECESSIVE_COMP_HET: 2.0
    AUTOSOMAL_RECESSIVE_HOM_ALT: 0.1
    MITOCHONDRIAL: 0.2
    X_DOMINANT: 0.1
    X_RECESSIVE_COMP_HET: 2.0
    X_RECESSIVE_HOM_ALT: 0.1
  pathogenicitySources:
  - REVEL
  - MVP
  ped: null
  proband: null
  steps:
  - failedVariantFilter: {}
  - variantEffectFilter:
      remove:
      - FIVE_PRIME_UTR_EXON_VARIANT
      - FIVE_PRIME_UTR_INTRON_VARIANT
      - THREE_PRIME_UTR_EXON_VARIANT
      - THREE_PRIME_UTR_INTRON_VARIANT
      - NON_CODING_TRANSCRIPT_EXON_VARIANT
      - NON_CODING_TRANSCRIPT_INTRON_VARIANT
      - CODING_TRANSCRIPT_INTRON_VARIANT
      - UPSTREAM_GENE_VARIANT
      - DOWNSTREAM_GENE_VARIANT
      - INTERGENIC_VARIANT
      - REGULATORY_REGION_VARIANT
  - frequencyFilter:
      maxFrequency: 2.0
  - pathogenicityFilter:
      keepNonPathogenic: true
  - inheritanceFilter: {}
  - omimPrioritiser: {}
  - hiPhivePrioritiser: {}
  vcf:
outputOptions:
  numGenes: 0
  outputContributingVariantsOnly: false
  outputFormats:
  - TSV_VARIANT
