############## 运行提示 ################
# 请提前准备好数据库 || 需要自行修改脚本
# python3 https://github.com/pzweuj/MyDockerImagePublic/blob/main/autocnv/create-database.py

# 需要mount进所有目录
# docker run -it --rm -v /autocnv_data:/opt/autocnv/data -v /vep_data:/root/.vep -v /ref_data:/ref_data autocnv:20241223

# 第一个命令，先调整autopvs1的配置文件
# cp self.config.ini /opt/autopvs1/config.ini

# 建议自行构建，适配自己的VEP数据库版本
#######################################

FROM ensemblorg/ensembl-vep:release_112.0

# 切换到root用户
USER root

# 基础依赖
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    python3 \
    python3-pip \
    curl \
    wget \
    expat \
    libdb-dev \
    openssl \
    tabix \
    && rm -rf /var/lib/apt/lists/*

# 安装python依赖库
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir \
    pandas \
    pyfaidx \
    pysam \
    gtfparse==1.2.1

# 切换工作目录
WORKDIR /opt

# 安装AutoPVS1 || 注意python版本
RUN git clone -b dev https://github.com/pzweuj/autopvs1.git && \
    cd autopvs1 && \
    python3 setup.py install && \
    chmod -R 777 /usr/local/lib/python3.10/dist-packages/autopvs1-0.1.0-py3.10.egg

# 安装AutoCNV
RUN git clone -b dev https://github.com/pzweuj/autocnv.git && \
    cd autocnv && \
    python3 setup.py install && \
    chmod -R 777 /usr/local/lib/python3.10/dist-packages/autocnv-0.1.0-py3.10.egg

# 标准进入点
USER vep
ENTRYPOINT ["/bin/bash"]

# 设置环境变量
LABEL maintainer='pzweuj' version='20241224' vep='v112' autopvs1='v2.0' autocnv='e25ca01'
