############## 运行提示 ################
# 需要mount进所有目录
# docker run -it --rm -v /autocnv_data:/opt/autocnv/data -v /vep_data:/root/.vep -v /ref_data:/ref_data autocnv:20241220

# 第一个命令，先调整autopvs1的配置文件
# cp self.config.ini /opt/autopvs1/config.ini
#######################################

FROM alpine:3.20.3

# 安装基础依赖
RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk update && apk add --no-cache \
    python3 \
    python3-dev \
    py3-pip \
    perl \
    perl-dev \
    R \
    R-dev \
    build-base \
    zlib-dev \
    bzip2-dev \
    xz-dev \
    git \
    curl \
    && rm -rf /var/cache/apk/*

# 安装perl依赖库
RUN apk add --no-cache \
    perl-archive-zip \
    perl-dbi \
    perl-dbd-mysql \
    perl-app-cpanminus \
    perl-json \
    && cpanm Bio::DB::BigFile \
    IO::Compress \
    HTTP::Tiny \
    List::MoreUtils \
    LWP::Simple \
    Bio::DB::HTS

WORKDIR /opt
# 安装VEP
RUN git clone https://github.com/Ensembl/ensembl-vep.git && \
    cd ensembl-vep && \
    perl INSTALL.pl --AUTO a

# 安装python依赖库
RUN python3 -m venv /opt/venv && /opt/venv/bin/pip install --no-cache-dir --upgrade pip && /opt/venv/bin/pip install --no-cache-dir \
    pandas \
    pyfaidx \
    pysam \
    gtfparse==1.2.1

# 安装AutoPVS1
RUN git clone https://github.com/JiguangPeng/autopvs1.git && \
    cd autopvs1 && \
    /opt/venv/bin/pip install -e .

# 安装AutoCNV
RUN git clone https://github.com/zhonghua-wang/autocnv.git

# 设置环境变量
ENV PATH="/opt/venv/bin:$PATH"
LABEL maintainer='pzweuj' version='20241220' vep='v113' autopvs1='v2.0' autocnv='e25ca01'
