############## 运行提示 ################
# 需要mount进所有目录
# docker run -it --rm -v /autocnv_data:/opt/autocnv/data -v /vep_data:/root/.vep -v /ref_data:/ref_data autocnv:20241220

# 第一个命令，先调整autopvs1的配置文件
# cp self.config.ini /opt/autopvs1/config.ini
#######################################

# 构建基础环境
FROM alpine:3.20.3 as builder

# 安装基础依赖
RUN apk update && apk add --no-cache \
    build-base \
    git \
    perl \
    perl-dev \
    zlib-dev \
    bzip2-dev \
    xz-dev \
    curl \
    wget \
    expat-dev \
    db-dev \
    openssl-dev \
    && rm -rf /var/cache/apk/*

# 设置VEP环境变量
ENV OPT /opt/vep
ENV OPT_SRC $OPT/src
ENV HTSLIB_DIR $OPT_SRC/htslib

# 创建工作目录
WORKDIR $OPT_SRC

# 下载并安装htslib（Bio::DB::HTS的依赖）
RUN git clone --depth 1 https://github.com/samtools/htslib.git && \
    cd htslib && \
    make && \
    make install

# 第二阶段：最终镜像
FROM alpine:3.20.3

# 安装基础依赖
RUN apk update && apk add --no-cache \
    python3 \
    python3-dev \
    py3-pip \
    perl \
    perl-dev \
    build-base \
    zlib-dev \
    bzip2-dev \
    xz-dev \
    git \
    curl \
    perl-archive-zip \
    perl-dbi \
    perl-dbd-mysql \
    perl-app-cpanminus \
    perl-json \
    perl-xml-parser \
    perl-xml-libxml \
    perl-xml-sax \
    perl-xml-twig \
    expat-dev \
    db-dev \
    openssl-dev \
    && rm -rf /var/cache/apk/*

# 复制第一阶段构建的htslib
COPY --from=builder /usr/local/lib/libhts* /usr/local/lib/
COPY --from=builder /usr/local/include/htslib /usr/local/include/htslib
COPY --from=builder /usr/local/bin/bgzip /usr/local/bin/
COPY --from=builder /usr/local/bin/tabix /usr/local/bin/

# 安装perl依赖
RUN cpanm --notest \
    Bio::Seq \
    DB_File \
    XML::Parser::PerlSAX \
    XML::DOM \
    Bio::DB::BigFile \
    IO::Compress \
    HTTP::Tiny \
    List::MoreUtils \
    LWP::Simple \
    Bio::DB::HTS

# 后续步骤
WORKDIR /opt

# 安装VEP
RUN git clone https://github.com/Ensembl/ensembl-vep.git && \
    cd ensembl-vep && \
    perl INSTALL.pl --AUTO a

# 安装python依赖库
RUN python3 -m venv /opt/venv && /opt/venv/bin/pip install --no-cache-dir --upgrade pip && \
    /opt/venv/bin/pip install --no-cache-dir \
    pandas \
    pyfaidx \
    pysam \
    gtfparse==1.2.1

# 安装AutoPVS1
RUN git clone https://github.com/JiguangPeng/autopvs1.git && \
    cd autopvs1 && \
    /opt/venv/bin/pip install -e .

# 安装AutoCNV
RUN git clone https://github.com/zhonghua-wang/autocnv.git

# 设置环境变量
ENV PATH="/opt/venv/bin:$PATH"
LABEL maintainer='pzweuj' version='20241223' vep='v113' autopvs1='v2.0' autocnv='e25ca01'
