FROM alpine:3.20.3

# 安装基础依赖
RUN apk update && apk add --no-cache \
    python3 \
    py3-pip \
    perl \
    perl-dev \
    R \
    R-dev \
    build-base \
    git \
    curl \
    && rm -rf /var/cache/apk/*

# 安装python依赖库
RUN python3 -m venv /opt/venv && /opt/venv/bin/pip install --no-cache-dir --upgrade pip && /opt/venv/bin/pip install --no-cache-dir \
    pandas \
    pyfaidx \
    pysam \
    gtfparse==1.2.1

# 安装perl依赖库
RUN apk add --no-cache \
    perl-archive-zip \
    perl-dbi \
    perl-dbd-mysql \
    perl-app-cpanminus \
    perl-json \
    && cpanm Bio::DB::BigFile \
    IO::Compress \
    Bio::DB::HTS \
    HTTP::Tiny \
    List::MoreUtils \
    LWP::Simple

# 安装VEP
RUN git clone https://github.com/Ensembl/ensembl-vep.git && \
    cd ensembl-vep && \
    perl INSTALL.pl --AUTO a

# 安装AutoPVS1
RUN git clone https://github.com/JiguangPeng/autopvs1.git && \
    cd autopvs1 && \
    /opt/venv/bin/pip install -e .

# 安装AutoCNV
RUN git clone https://github.com/zhonghua-wang/autocnv.git


ENV PATH="/opt/venv/bin:$PATH"

LABEL maintainer='pzweuj' version='2024122001' vep='v113' autopvs1='v2.0' autocnv='e25ca01'
