name: Build and Push Docker Images

on:
  push:
    paths:
      - '**/dockerfile'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.set-output.outputs.changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed Dockerfiles
        id: detect
        run: |
          echo "Finding changed Dockerfiles..."
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep 'Dockerfile' || true)
          echo "Changed Dockerfiles: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Extract Commit Message
        id: extract_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          FORMATTED_MSG=$(echo "$COMMIT_MSG" | tr ' ' '-' | tr -d '\n' | tr -cd '[:alnum:]-')
          echo "Commit Message: $FORMATTED_MSG"
          echo "COMMIT_MESSAGE=$FORMATTED_MSG" >> $GITHUB_ENV

  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.changed_files != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Images
        run: |
          for file in ${{ needs.detect-changes.outputs.changed_files }}; do
            echo "Building and pushing image for $file..."
            dir=$(dirname $file)
            docker build -t ghcr.io/${{ github.repository_owner }}/$dir:${{ env.COMMIT_MESSAGE }} -f $file .
            echo "Pushing image ghcr.io/${{ github.repository_owner }}/$dir:${{ env.COMMIT_MESSAGE }}..."
            docker push ghcr.io/${{ github.repository_owner }}/$dir:${{ env.COMMIT_MESSAGE }}
          done
