name: Build and Push Docker Images

on:
  push:
    paths:
      - '**/dockerfile'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.detect.outputs.changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changed Dockerfiles
        id: detect
        run: |
          echo "Finding changed Dockerfiles..."
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep 'Dockerfile' || true)
          echo "Changed Dockerfiles: $CHANGED_FILES"
          echo "changed_files='${CHANGED_FILES}'" >> $GITHUB_OUTPUT

      - name: Extract Commit Message
        id: extract_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          FORMATTED_MSG=$(echo "$COMMIT_MSG" | tr ' ' '-' | tr -d '\n' | tr -cd '[:alnum:]-')
          echo "Commit Message: $FORMATTED_MSG"
          echo "COMMIT_MESSAGE=$FORMATTED_MSG" >> $GITHUB_ENV

      - name: Debug Output
        run: |
          echo "GITHUB_OUTPUT content:"
          cat $GITHUB_OUTPUT
          echo "Changed files value:"
          echo "${{ steps.detect.outputs.changed_files }}"

  build:
    needs: detect-changes
    if: ${{ contains(needs.detect-changes.outputs.changed_files, 'Dockerfile') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Images
        run: |
          for file in ${{ needs.detect-changes.outputs.changed_files }}; do
            echo "Building and pushing image for $file..."
            dir=$(dirname $file)
            docker build -t ghcr.io/${{ github.repository_owner }}/$dir:${{ env.COMMIT_MESSAGE }} -f $file .
            echo "Pushing image ghcr.io/${{ github.repository_owner }}/$dir:${{ env.COMMIT_MESSAGE }}..."
            docker push ghcr.io/${{ github.repository_owner }}/$dir:${{ env.COMMIT_MESSAGE }}
          done

      - name: Debug Changed Files
        run: |
          echo "Changed files from previous job:"
          echo "${{ needs.detect-changes.outputs.changed_files }}"
